apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      include /etc/nginx/mime.types;
      server {
        listen 80;

        location / {
          proxy_pass http://frontend:80;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/ {
          proxy_pass http://api-gateway:50000;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
      }
    }
