events {}

http {
  upstream api_gateway {
    server api-gateway:50000;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://frontend:80;
    }

    location /api/ {
      proxy_pass http://api_gateway;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;

    gzip on;
    gzip_types text/plain application/json;
  }
}