events {}

http {
  upstream api_gateway {
    server api-gateway:50000;
  }

  upstream frontend {
    server frontend:3000;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://frontend;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }

    location /api/ {
      proxy_pass http://api_gateway;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;

    gzip on;
    gzip_types text/plain application/json;
  }
}